name: Deploy to Staging

on:
  push:
    branches:
      - develop
  workflow_run:
    workflows: ["Testing and Analyzing"]
    types:
      - completed      

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check if Testing and Analyzing Workflow succeeded
      id: check-status
      run: echo "status=${{ github.event.workflow_run.conclusion == 'success' }}" >> $GITHUB_OUTPUT

    - name: Conditionally run if Testing and Analyzing fail
      if: steps.check-status.outputs.status == 'false'
      run: exit 1

    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Create env file
      run: echo "${{ secrets.CONFIG_ENV }}" > config.env

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.0'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: View tree
      run: ls -la

    - name: Create tarball
      run: tar -czf source_code.tar.gz .

    - name: Upload compressed file
      uses: actions/upload-artifact@v2
      with:
        name: source_code
        path: source_code.tar.gz

    - name: View tree
      run: ls -la      
