name: Deploy to Staging

on:
  push:
    branches:
      - develop
  workflow_run:
    workflows: ["Testing and Analyzing"]
    types:
      - completed      

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check if Testing and Analyzing Workflow succeeded
      id: check-status
      run: echo "status=${{ github.event.workflow_run.conclusion == 'success' }}" >> $GITHUB_OUTPUT

    - name: Conditionally run if Testing and Analyzing fail
      if: steps.check-status.outputs.status == 'false'
      run: exit 1

    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Create env file
      run: echo "${{ secrets.CONFIG_ENV }}" > config.env

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.0'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: View tree
      run: ls -la

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
         ls -la

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "./*"
        target: "/home/ubuntu/levanthinh"

    - name: Trigger Jenkins Job
      run: |
        curl -X POST \
          --user lethinh2003:${{ secrets.JENKINS_TOKEN }} \
          "http://20.188.118.32:8080/job/Testing/build"